name: Workflow 
on:
  push:
    branches:
      - feature-ms-AndresTapia

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validando tipo de proyecto
        id: tipoProyecto
        run: |
          if [ -f "build.gradlew" ]
          then
            echo "Proyecto Java"
            if grep -q 'id "orga.sonarqube" version "3.3"' build.gradle
            then
              echo "El plugin de SonarCloud ya esta presente en build.gradle"
            else
              sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
              echo "El plugin de SonarCloud no estaba presente y se ha añadido en build.gradle"
              cat build.gradle
              fi
            else
              echo "Tipo de proyecto desconocido"
            fi
      - name: Validando existencia de proyecto en SonarCloud
        id: validateProjectSonar
        run: |
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=andresatl' -d 'visibility=public'
          if [ $? -ne 0 ]
          then
            echo "Proyecto ya existe en Sonarcloud"
          else
            echo "Proyecto ${{ github.event.repository.name }} fue creado exitosamente en SonarCloud"

            echo "Se establece rama main como rama por defecto"
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main'  -d 'project=${{ github.event.repository.name }}'
          fi
              
              
      
    
